
name: Update Dashboard
on:
  schedule:
    - cron: '1 */6 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      - name: Generate dashboard
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
          THRESHOLDS: ${{ vars.THRESHOLDS_JSON }}
        run: |
          python toppreise_web_dashboard.py
      - name: Commit & push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore: update dashboard [skip ci]"
            git push
          fi
